### ISSUE TITLE
How do I use partialify/custom with grunt-browserify?

### ISSUE THREAD

**Issue by cheapsteak** [bclinkinbeard/partialify#13]
Can't pass `partialify/custom` in to the grunt config's `transform` array, gives the error:

> Error: Unexpected object exported by the "/Users/chang/work/jam3/testgenerator/node_modules/partialify/custom.js" package. Expected a transform function.

**Comment by bclinkinbeard** [comment]
The custom module returns a function that needs to be called 






On Mon, Jun 29, 2015 at 2:42 PM -0700, "Chang Wang" <notifications@github.com> wrote:












Can't pass partialify/custom in to the grunt config's transform array, gives the error:




Error: Unexpected object exported by the "/Users/chang/work/jam3/testgenerator/node_modules/partialify/custom.js" package. Expected a transform function.
