### ISSUE TITLE
Use partialify on command line with options

### ISSUE THREAD

**Issue by FuriouZz** [bclinkinbeard/partialify#15]
Hello,

I would like to use partialify with `.svg` files. I do not use any gulp and grunt, I use only the command line.
My current command line is this one : `browserify -t [ partialify ] index.js -o main.js`.

Is it possible to make something like `browserify -t [ partialify ".svg" ] index.js -o main.js` to add custom file ?

**Comment by bclinkinbeard** [comment]
There isn't any built-in CLI support at the moment, but I'd love a PR that added it. Barring that, the easiest thing is probably to point at a file that has contents like `module.exports = require('./custom').alsoAllow('svg');`

**Comment by FuriouZz** [comment]
I test this current syntax: 
```
browserify -t [ partialify --extensions [ svg ] ] app/ -o ./bundle.js
```

It is possible to access to the `extensions` array in the `partialify` function, in the `opts.extensions._` object. I think we can try to merge `types` and `opts.extensions._` values.

**Comment by bclinkinbeard** [comment]
Oh, sorry, I had forgotten how transforms work. :) You can use the following syntax with the existing version of `partialify`.

`browserify index.js -t [ partialify --alsoAllow svg ] -o bundle.js`
`browserify index.js -t [ partialify --alsoAllow svg --alsoAllow xml ] -o bundle.js`
`browserify index.js -t [ partialify --onlyAllow svg --onlyAllow tsv ] -o bundle.js`
