### ISSUE TITLE
Add option to apply transforms to partials before str2js?

### ISSUE THREAD

**Issue by ansballard** [bclinkinbeard/partialify#19]
Hello! Just wanted to see if this is within the scope of partialify, or if I'm going about it the wrong way. I'm pulling html templates via partialify, so they're getting thrown into my big ball of js, but they still have whitespace, comments, etc. So I added a quick line in the returned `through()` call to run through a list of transforms on the `opts` parameter.

``` javascript
return through(function (chunk) {
  buffer += chunk.toString();
},
  function () {
    if (buffer.indexOf('module.exports') === 0) {
      this.queue(buffer); // prevent "double" transforms
    } else {
      /* START CHANGE */
      if(opts && opts.transforms) {
        opts.transforms.forEach(function(t) {
          buffer = t(buffer);
        });
      }
      /* END CHANGE */
      this.queue(str2js(buffer));
    }
    this.queue(null);
  }
);
```

And here's what I'm passing in to browserify:

``` javascript
...
.transform(partialify, {
  transforms: [function(partial) { return htmlmin(partial, htmlminopts); }]
});
...
```

So is this something you'd consider to be within the scope of partialify to handle? Or should there be/is there some other transform that can be dropped in before partialify to minify html/css/etc?

Btw code snippets are super specific to my use case, will clean them up if necessary.

**Comment by bclinkinbeard** [comment]
Hey, thanks for the proposal, I appreciate it. I think it would be preferable to handle it with a separate transform that runs before partialify, rather than adding another nested level of transforms.
