### ISSUE TITLE
Minifying required html/css

### ISSUE THREAD

**Issue by psirenny** [bclinkinbeard/partialify#4]
What's the best way to go about minifying or applying other transforms on the files that partialify requires? I realize that partialify shouldn't be responsible for the minification. Is this a feature that should be added to partialify or does browserify already support nesting transforms in this way?

**Comment by DrewML** [comment]
+1 on this. @tjconcept, did you plan to work on that PR still? If not, I might be willing to pick it up.

**Comment by tjconcept** [comment]
Funny thing I actually revisited this last night, and had an in-my-head discussion on whether this was the right approach.

The problem with partialify in general (and a lot of similar modules) is that they "extend" the language. This is never going to work in anything else than a browserified context. This is contrary to a module like https://www.npmjs.com/package/brfs.

The result? Two very specific modules: https://github.com/paylike/bryles and https://github.com/paylike/brarkup. They will actually run in node as well.
These modules are of course way too tailored. It might be possible to implement independent static transforms for jade/slim, clean-css, Autoprefixer and Stylus in stead.
