### ISSUE TITLE
It's not clear what this plugin actually does

### ISSUE THREAD

**Issue by cowwoc** [bclinkinbeard/partialify#9]
I get the fact that you can `require()` css files, but the example code in README.md shows an output file `./bundle.js`.

Where does the resulting CSS files get written?
Are the CSS files bundled into one big CSS file?
Do we have to add a link in the HTML file to the resulting CSS file or is it done for us automatically?
etc...

It would help if you provided a sample project showing the input files, configuration and output files. This way we can examine what the plugin actually does before refactoring our own projects.

**Comment by bclinkinbeard** [comment]
It's a Browserify transform. 

`css = require('./some.css')` just puts the contents of some.css into the css var.

**Comment by cowwoc** [comment]
I'm sure this sounds silly to you, but I think you should mention this fact in README.md. It's not obvious to a first-time browserify user (I've never used transforms before).

**Comment by bclinkinbeard** [comment]
The third line of the readme states "To use, specify as a Browserify transform..."

**Comment by cowwoc** [comment]
@bclinkinbeard Agreed, but my point remains: this explains how to use the plugin, not what it does. Someone who has never used transforms before won't be able to figure out what this plugin is about.

**Comment by panzerdp** [comment]
:)

**Comment by tannerlinsley** [comment]
I agree. I expected a `var`-less `require('some.css')` to inline my css into some self-executing function.

**Comment by bclinkinbeard** [comment]
https://github.com/bclinkinbeard/partialify/commit/8aa65e9f5561ef9dedec65ad778ed56205f92186
